# Generated by Django 5.0.2 on 2024-02-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=50)),
                ('number_of_members', models.IntegerField()),
                ('year_formed', models.DateField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
