# Generated by Django 5.0.2 on 2024-02-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theband', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='about_the_band',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
