# Generated by Django 5.0.2 on 2024-02-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theband', '0002_band_about_the_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='about_the_band',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
